$script_nginx = <<-SCRIPT
  apt install -y nginx
SCRIPT

$script_mysql = <<-SCRIPT
  apt install -y mysql-server-5.7 && \
  mysql -e "create user 'admin'@'%' identified by 'admin';"
  # cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf
  # service mysql restart
SCRIPT

$script_key = <<-SCRIPT
  cat /configs/id_bionic.pub >> .ssh/authorized_keys
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.network "public_network", ip: "192.168.1.28"

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "./configs", "/configs"

  config.vm.provision "shell", inline: "apt update"
  config.vm.provision "shell", inline: $script_nginx
  config.vm.provision "shell", inline: $script_mysql
  config.vm.provision "shell", inline: $script_key
end