$script_ansible_install = <<-SCRIPT
  apt update && \
  apt install -y software-properties-common && \
  apt-add-repository --yes --update ppa:ansible/ansible && \
  apt install ansible -y
SCRIPT

$script_ansible_run = <<-SCRIPT
  ansible-playbook -i /vagrant/configs/ansible/hosts /vagrant/configs/ansible/playbook.yml
SCRIPT

$script_pri_key = <<-SCRIPT
  cp /vagrant/configs/keys/id_ed25519 /home/vagrant && \
  chmod 600 /home/vagrant/id_ed25519 && \
  chown vagrant:vagrant /home/vagrant/id_ed25519
SCRIPT

$script_pub_key = <<-SCRIPT
  cat /vagrant/configs/keys/id_ed25519.pub >> .ssh/authorized_keys
SCRIPT

$script_puppet = <<-SCRIPT
  apt-get update && \
  apt-get install -y puppet
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.define "mysql" do |mysql|
    mysql.vm.network "public_network", ip: "192.168.1.100"
    mysql.vm.provision "shell", inline: $script_pub_key
  end

  config.vm.define "php" do |php|
    php.vm.network "forwarded_port", guest: 8888, host: 8888
    php.vm.network "public_network", ip: "192.168.1.101"

    php.vm.provision "shell", inline: $script_pub_key
    php.vm.provision "shell", inline: $script_puppet

    php.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "php.pp"
    end
  end

  config.vm.define "ansible" do |ansible|
    ansible.vm.network "public_network", ip: "192.168.1.102"
    ansible.vm.provision "shell", inline: $script_pri_key
    ansible.vm.provision "shell", inline: $script_ansible_install
    ansible.vm.provision "shell", inline: $script_ansible_run
  end
end
